### ISSUE TITLE
SpriteSheet filteringMode

### ISSUE THREAD

**Issue by AlexHedley** [subdigital/minesweeper-swift#1]
In `Shared`

`SpriteSheet.swift`

`func textureFor(row: Int, col: Int, filteringMode: SKTextureFilteringMode = .nearest) -> SKTexture?`

`texture.filteringMode = .nearest`

Should this be:

`texture.filteringMode = filteringMode`

**Comment by subdigital** [comment]
🤦‍♂️ yep!  Good catch. Want to submit a PR for this fix?

**Comment by AlexHedley** [comment]
Sure
